//
// CreateClient.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateClient: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var secret: String?
    public var name: String
    public var description: String?
    public var services: AnyCodable?

    public init(id: UUID? = nil, secret: String? = nil, name: String, description: String? = nil, services: AnyCodable? = nil) {
        self.id = id
        self.secret = secret
        self.name = name
        self.description = description
        self.services = services
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case secret
        case name
        case description
        case services
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(services, forKey: .services)
    }
}

