"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth
from auth.model.client import Client


class TestClient(unittest.TestCase):
    """Client unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClient(self):
        """Test Client"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Client()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
