"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import unittest

import auth
from auth.api.clients_api import ClientsApi  # noqa: E501


class TestClientsApi(unittest.TestCase):
    """ClientsApi unit test stubs"""

    def setUp(self):
        self.api = ClientsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_client(self):
        """Test case for create_client

        """
        pass

    def test_destroy_client(self):
        """Test case for destroy_client

        """
        pass

    def test_list_clients(self):
        """Test case for list_clients

        """
        pass

    def test_partial_update_client(self):
        """Test case for partial_update_client

        """
        pass

    def test_retrieve_client(self):
        """Test case for retrieve_client

        """
        pass

    def test_update_client(self):
        """Test case for update_client

        """
        pass


if __name__ == '__main__':
    unittest.main()
