"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import unittest

import auth
from auth.api.init_api import InitApi  # noqa: E501


class TestInitApi(unittest.TestCase):
    """InitApi unit test stubs"""

    def setUp(self):
        self.api = InitApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_init(self):
        """Test case for create_init

        """
        pass


if __name__ == '__main__':
    unittest.main()
