"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auth
from auth.model.create_client import CreateClient


class TestCreateClient(unittest.TestCase):
    """CreateClient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateClient(self):
        """Test CreateClient"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateClient()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
