"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import unittest

import auth
from auth.api.authorize_api import AuthorizeApi  # noqa: E501


class TestAuthorizeApi(unittest.TestCase):
    """AuthorizeApi unit test stubs"""

    def setUp(self):
        self.api = AuthorizeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_authorize(self):
        """Test case for create_authorize

        """
        pass


if __name__ == '__main__':
    unittest.main()
