# Generated by Django 4.1.1 on 2022-09-10 06:07

import api.models
import api.utils.auth
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('key', models.CharField(default=api.utils.auth.generate_access_key, max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(default=api.models.generate_secret, editable=False, max_length=128)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
