# Generated by Django 4.1.1 on 2022-09-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='services',
            field=models.JSONField(default=[]),
        ),
    ]
